apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: harbor-credentials
  namespace: imagepull
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.localhost.com": {
          "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }
