apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-artifacts
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: "standard"